name: Build

on: push

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17', '21' ]
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - run: ./mvnw clean verify -B -V -e -ntp
